const adminActionTypes = {
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
  ADMIN_REGISTER_FAIL: "ADMIN_REGISTER_FAIL",
  ADMIN_LOGOUT: "ADMIN_LOGOUT",
};

export default adminActionTypes;
