const studentActionTypes = {
  STUDENT_LOGIN_SUCCESS: "STUDENT_LOGIN_SUCCESS",
  STUDENT_LOGIN_FAIL: "STUDENT_LOGIN_FAIL",
  STUDENT_REGISTER_SUCCESS: "STUDENT_REGISTER_SUCCESS",
  STUDENT_REGISTER_FAIL: "STUDENT_REGISTER_FAIL",
  STUDENT_LOGOUT: "STUDENT_LOGOUT",
};

export default studentActionTypes;
