const teacherActionTypes = {
  TEACHER_LOGIN_SUCCESS: "TEACHER_LOGIN_SUCCESS",
  TEACHER_LOGIN_FAIL: "TEACHER_LOGIN_FAIL",
  TEACHER_REGISTER_SUCCESS: "TEACHER_REGISTER_SUCCESS",
  TEACHER_REGISTER_FAIL: "TEACHER_REGISTER_FAIL",
  TEACHER_LOGOUT: "TEACHER_LOGOUT",
};

export default teacherActionTypes;
